[package]
name = "bacik"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "tls-rustls", "sqlite", "chrono"] }
tokio = { version = "1.43.0", features = ["full", "macros"] }
